// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nthduutecbjkvouvyycj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50aGR1dXRlY2Jqa3ZvdXZ5eWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDY5NzcsImV4cCI6MjA3NDIyMjk3N30.aJ_OP9BOwMSgBm4zjGP0-j39GUrEFSHLHSjMzFm3HGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});